# Generated by Django 4.2.11 on 2026-02-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0002_auto_20201212_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dronecomponentcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
